"""Regenerate native runtime locks: uv run --no-project python scripts/lock-gpu.py."""

import re
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def is_gpu(name):
    return name.startswith("nvidia-") or name in {"torch", "torchvision", "triton"}


def main():
    # Export without resolving/upgrading the existing workspace lock.
    exported = subprocess.check_output(
        [
            "uv",
            "export",
            "--frozen",
            "--package",
            "openspline-server",
            "--extra",
            "gpu",
            "--extra",
            "demo",
            "--extra",
            "livekit",
            "--extra",
            "distributed",
            "--no-dev",
            "--no-emit-workspace",
        ],
        cwd=ROOT,
        text=True,
    )
    # CUDA libraries must travel with their matching torch wheel, not the PyPI default.
    blocks = re.split(r"(?=^[a-zA-Z0-9][a-zA-Z0-9_.-]*==)", exported, flags=re.M)
    common = "# Generated by scripts/lock-gpu.py; install with one cuda runtime lock.\n"
    for block in blocks:
        name = block.split("==", 1)[0]
        if re.fullmatch(r"[a-zA-Z0-9_.-]+", name) and not is_gpu(name):
            common += block
    (ROOT / "requirements/server.txt").write_text(common)
    with tempfile.TemporaryDirectory() as directory:
        source = Path(directory) / "runtime.in"
        for runtime in ("cu126", "cu128"):
            source.write_text(f"torch==2.7.1+{runtime}\ntorchvision==0.22.1+{runtime}\n")
            subprocess.run(
                [
                    "uv",
                    "pip",
                    "compile",
                    str(source),
                    "--generate-hashes",
                    "--no-header",
                    "--no-annotate",
                    "--python-version",
                    "3.11",
                    "--python-platform",
                    "x86_64-unknown-linux-gnu",
                    "--torch-backend",
                    runtime,
                    "--constraint",
                    "requirements/server.txt",
                    "--output-file",
                    f"requirements/{runtime}.txt",
                ],
                cwd=ROOT,
                check=True,
                stdout=subprocess.DEVNULL,
            )
            output = ROOT / f"requirements/{runtime}.txt"
            blocks = re.split(r"(?=^[a-zA-Z0-9][a-zA-Z0-9_.-]*==)", output.read_text(), flags=re.M)
            output.write_text(
                "# Generated by scripts/lock-gpu.py; pair with server.txt and --torch-backend "
                + runtime
                + ".\n"
                + "".join(block for block in blocks if is_gpu(block.split("==", 1)[0]))
            )


if __name__ == "__main__":
    main()
